FROM node:10.13.0-alpine

# Create app directory
WORKDIR /app/server/

COPY /Server /app/server/

RUN npm install
# If you are building your code for production (ignores files in dev dependencies)
#RUN npm install --production

RUN npm install typescript -g

RUN npm run typeorm migration:run

CMD node -r ts-node/register/transpile-only src/index.ts

EXPOSE 8080
