FROM node:10.13.0-alpine

# Create app directory
WORKDIR /app/server

COPY /Server/package*.json /app/server/
COPY /Server/tsconfig*.json /app/server/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

COPY /Server .

CMD npm run typeorm migration:run
CMD npm run start:dev

EXPOSE 8080
