FROM node:12.12.0-alpine

# Create app directory
WORKDIR /app/website/

COPY /Website/menupls-web /app/website/

RUN npm install

RUN npm rebuild node-sass

RUN npm install -g serve

RUN npm run build

CMD serve -s build -l 4000

EXPOSE 4000
