version: "2"

services:
  restaurants-menu-proxy:
    build:
      context: ../..
      dockerfile: conf/proxy/Dockerfile.proxy
    environment:
      - API_HOST=${HOSTNAME}
      - API_PORT=${API_PORT}
      - WEBSITE_PORT=${WEBSITE_PORT}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../dev-certs:/etc/nginx/certs
    networks:
     -  restaurants-network
  restaurants-menu-website:
    build:
      context: ../..
      dockerfile: conf/Website/Dockerfile.prod
    ports:
      - ${WEBSITE_PORT}:4000
    volumes:
      - ../dev-certs:/app/website/certs
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}
  restaurants-menu-app:
    build:
      context: ../..
      dockerfile: conf/Server/Dockerfile.prod
    ports:
      - ${API_PORT}:8080
    volumes:
      - ../dev-certs:/app/server/certs
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}

networks:
  restaurants-network: