version: '2.2'

services:
  restaurants-menu-proxy:
    build:
      context: ../..
      dockerfile: conf/proxy/Dockerfile.proxy
    environment:
      - API_HOST=${HOSTNAME}
      - API_PORT=${API_PORT}
      - WEBSITE_PORT=${WEBSITE_PORT}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../dev-certs:/etc/nginx/certs
    networks:
     -  restaurants-network
  restaurants-menu-website:
    environment:
      - SKIP_PREFLIGHT_CHECK=${SKIP_PREFLIGHT_CHECK}
      - REACT_APP_API_BASE_URL=https://${HOSTNAME}
    build:
      context: ../..
      dockerfile: conf/Website/Dockerfile.prod
    ports:
      - ${WEBSITE_PORT}:4000
    volumes:
      - ../dev-certs:/app/website/certs
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}
  restaurants-menu-app:
    environment:
      - API_HOST=${HOSTNAME}
      - REACT_APP_HOSTNAME=https://${HOSTNAME}
      - API_PORT=${API_PORT}
      - ES_HOST=https://${HOSTNAME}:9200
      - ES_PASSWORD=${ES_PASSWORD}
      - APP_ENV=${APP_ENV}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_PUBLIC_URL_PREFIX=${AWS_PUBLIC_URL_PREFIX}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    build:
      context: ../..
      dockerfile: conf/Server/Dockerfile.prod
    ports:
      - ${API_PORT}:8080
    volumes:
      - ../dev-certs:/app/server/certs
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - ELASTIC_PASSWORD=${ES_PASSWORD}
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=${ES_CERTS_DIR}/privkey.pem
      - xpack.security.http.ssl.certificate=${ES_CERTS_DIR}/fullchain.pem
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate=${ES_CERTS_DIR}/fullchain.pem
      - xpack.security.transport.ssl.key=${ES_CERTS_DIR}/privkey.pem
    volumes:
      - ../dev-certs:${ES_CERTS_DIR}
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      restaurants-network:
        aliases:
          - ${HOSTNAME}

volumes:
  es_data:

networks:
  restaurants-network: